version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Pass@word1
      - POSTGRES_DB=taskdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
